# -----------------------------------------------------------------------------
# @author    Auto-generated by STM32CubeIDE for Visual Studio Code Extension
# -----------------------------------------------------------------------------
# @attention
#
# Copyright (c) 2025 STMicroelectronics.
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.
#
# -----------------------------------------------------------------------------

# This is converter generated file, and shall not be touched by user
#
# Use CMakeLists.txt to apply user changes
cmake_minimum_required(VERSION 3.20)

# Core MCU flags, CPU, instruction set and FPU setup
set(cpu_PARAMS ${CPU_FLAGS} ${cpu_PARAMS})

# Linker script
set(linker_script_SRC ${linker_script_SRC}
	${CMAKE_CURRENT_SOURCE_DIR}/stm32c5a3xg_flash.ld
)

# Sources
set(sources_SRCS ${sources_SRCS}
	${CMAKE_CURRENT_SOURCE_DIR}/Src/syscall.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/sysmem.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/system_stm32c5xx.c
	${CMAKE_CURRENT_SOURCE_DIR}/Src/startup_stm32c5a3xx.c
)

# Include directories
set(include_c_DIRS ${include_c_DIRS}
	${CMAKE_CURRENT_SOURCE_DIR}/packs/STMicroelectronics.stm32c5xx_dfp.2.0.0/Include/
	${CMAKE_CURRENT_SOURCE_DIR}/packs/STMicroelectronics.CMSIS.6.3.0/CMSIS/Core/Include/
)
set(include_cxx_DIRS ${include_cxx_DIRS}
)
set(include_asm_DIRS ${include_asm_DIRS}
)

# Symbols definition
set(symbols_c_SYMB ${symbols_c_SYMB}
	RTE_DEVICE_STARTUP_STM32C5XX
	STM32C5A3xx
)
set(symbols_cxx_SYMB ${symbols_cxx_SYMB}
)
set(symbols_asm_SYMB ${symbols_asm_SYMB}
)

# Link directories
set(link_DIRS ${link_DIRS}
)

# Link libraries
set(link_LIBS ${link_LIBS}
)

# Compiler options
set(compiler_OPTS ${compiler_OPTS} ${SECURE_FLAGS})

# Linker options
set(linker_OPTS ${linker_OPTS})
