/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "init.h"
#include "led.h"
#include "segment_display.h"
#include "state_1.h"
#include "state_2.h"
#include "state_3.h"

static void delay(uint32_t count) {
    while (count--) {
        __asm("nop");
    }
}

int main(void)
{
    uint8_t state = 1;
    uint8_t previous_button_state = 0;

    system_init();
    led_all_off();
    led_set(state - 1, 1);
    segment_display_clear();

    while (1) {
        uint8_t current_button_state = (GPIOC->IDR & PIN_MASK(USER_BUTTON_PIN)) != 0;

        if (current_button_state && !previous_button_state) {
            state++;
            if (state > LED_COUNT) {
                state = 1;
            }
            delay(500000);  // Debounce delay
            led_all_off();
            led_set(state - 1, 1);
                
        }

        previous_button_state = current_button_state;

        // Always run the current state
        switch (state) {
            case 1:
                state_1_run();
                break;
            case 2:
                state_2_run();
                break;
            case 3:
                state_3_run();
                break;
        }

    }
}