/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "init.h"
#include "led.h"
#include "segment_display.h"
#include "state_1.h"
#include "state_2.h"
#include "state_3.h"
#include "state_4.h"

typedef enum {
    APP_STATE_1 = 1u,
    APP_STATE_2 = 2u,
    APP_STATE_3 = 3u,
    APP_STATE_4 = 4u
} AppState;

static void delay_cycles(uint32_t count) {
    while (count--) {
        __asm("nop");
    }
}

static uint8_t user_button_is_pressed(void)
{
    return (GPIOC->IDR & PIN_MASK(USER_BUTTON_PIN)) != 0u;
}

static void update_state_led(AppState state)
{
    led_all_off();

    if (state == APP_STATE_4) {
        for (uint8_t led_index = 0u; led_index < LED_COUNT; ++led_index) {
            led_set(led_index, 1u);
        }
        return;
    }

    led_set((uint8_t)state - 1u, 1u);
}

static AppState advance_state(AppState state)
{
    if (state == APP_STATE_4) {
        return APP_STATE_1;
    }

    return (AppState)((uint8_t)state + 1u);
}

static void run_active_state(AppState state)
{
    switch (state) {
        case APP_STATE_1:
            state_1_run();
            break;

        case APP_STATE_2:
            state_2_run();
            break;

        case APP_STATE_3:
            state_3_run();
            break;

        case APP_STATE_4:
            state_4_run();
            break;

        default:
            segment_display_clear();
            break;
    }
}

int main(void)
{
    AppState state = APP_STATE_1;
    uint8_t previous_button_state = 0u;

    system_init();
    state_2_init();
    update_state_led(state);
    segment_display_clear();

    while (1) {
        uint8_t current_button_state = user_button_is_pressed();

        if ((current_button_state != 0u) && (previous_button_state == 0u)) {
            state = advance_state(state);
            update_state_led(state);
            delay_cycles(500000u);
        }

        previous_button_state = current_button_state;
        run_active_state(state);
    }
}