/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32c5a3xx.h"

#define LD1_PORT GPIOA
#define LD1_PIN 5  // PA5
#define LD2_PORT GPIOG
#define LD2_PIN 1  // PG1
#define LD3_PORT GPIOG
#define LD3_PIN 2  // PG2
#define USER_BUTTON_PIN 13  // PC13
#define LED_COUNT 3

#define PIN_MASK(pin) (1U << (pin))

typedef struct {
    GPIO_TypeDef *port;
    uint32_t pinMask;
    uint8_t activeLow;
} LedConfig;

static const LedConfig leds[LED_COUNT] = {
    { LD1_PORT, PIN_MASK(LD1_PIN), 0 },
    { LD2_PORT, PIN_MASK(LD2_PIN), 1 },
    { LD3_PORT, PIN_MASK(LD3_PIN), 1 },
};

static void delay(uint32_t count) {
    while (count--) {
        __asm("nop");
    }
}

static void set_pin_output(GPIO_TypeDef *port, uint32_t pin) {
    uint32_t shift = pin * 2;
    port->MODER &= ~(3U << shift);  // Clear the two mode bits
    port->MODER |=  (1U << shift);  // Set mode = 01 (output)
}

static inline void led_write(const LedConfig *led, uint8_t on) {
    if (on) {
        if (led->activeLow) {
            led->port->ODR &= ~led->pinMask;
        } else {
            led->port->ODR |= led->pinMask;
        }
    } else {
        if (led->activeLow) {
            led->port->ODR |= led->pinMask;
        } else {
            led->port->ODR &= ~led->pinMask;
        }
    }
}

static inline void led_on(const LedConfig *led) {
    led_write(led, 1);
}

static inline void led_off(const LedConfig *led) {
    led_write(led, 0);
}

static void system_init(void) {
    // Enable GPIOA, GPIOG and GPIOC clocks
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN | RCC_AHB2ENR_GPIOGEN | RCC_AHB2ENR_GPIOCEN;

    // Make LD1, LD2 and LD3 output pins
    set_pin_output(leds[0].port, LD1_PIN);
    set_pin_output(leds[1].port, LD2_PIN);
    set_pin_output(leds[2].port, LD3_PIN);

    // Make USER button pin input
    GPIOC->MODER &= ~(3U << (USER_BUTTON_PIN * 2));

    // Turn all LEDs off initially
    led_off(&leds[0]);
    led_off(&leds[1]);
    led_off(&leds[2]);
}

static void led_indicator(uint8_t state) {
    // Turn all LEDs off first
    for (uint32_t i = 0; i < LED_COUNT; i++) {
        led_off(&leds[i]);
    }

    // Then turn on the LED for the selected state
    if (state >= 1 && state <= LED_COUNT) {
        led_on(&leds[state - 1]);
    }
}

int main(void)
{
    uint8_t state = 1;  // Start with LD1 on
    uint8_t previous_button_state = 0;

    system_init();
    led_indicator(state);

    while (1) {
        uint8_t current_button_state = (GPIOC->IDR & (1U << USER_BUTTON_PIN)) != 0;

        // Detect a fresh button press only on the rising edge
        if (current_button_state && !previous_button_state) {
            state++;
            if (state > 3) {
                state = 1;
            }
            delay(500000);  // Simple debounce delay
            led_indicator(state);
        }

        previous_button_state = current_button_state;
    }
}
