/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "init.h"
#include "segment_display.h"

int main(void)
{
    board_init();
    segment_display_init();

    uint32_t counter = 0u;

    for (;;)
    {
        segment_display_show((float)counter);
        counter = (counter + 1u) % 10000u;
    }
}
